version: "3.7"

services:

    rebackend:
        image: "airstorage/backend:dev"
        build:
            target: dev
            context: ./rebackend
        volumes:
            - ./rebackend:/usr/src/app

    frontend:
        image: "airstorage/frontend:dev"
        build:
            target: dev
            context: ./refrontend
        volumes:
            - ./refrontend:/usr/src/app
        ports:
            - "8800:80"

    renginx:
        image: "airstorage/nginx:dev"
        build:
            target: prod
            context: ./renginx
