version: "3.7"

services:

    frontend:
        image: "airstorage/frontend:prod"
        build:
            target: prod
            context: ./refrontend

    rebackend:
        command: "gunicorn -b 0.0.0.0:80 --error-logfile - server:app"
        image: "airstorage/backend:prod"
        build:
            target: prod
            context: ./rebackend
        networks:
            - private
            - public
        labels:
            - "traefik.enable=false"
        volumes:
            - "./rebackend/database.db:/usr/src/app/database.db"
    
    renginx:
        command: nginx -g "daemon off";
        image: "airstorage/nginx:prod"
        build:
            target: prod
            context: ./renginx
        networks:
            - private
            - public
        labels:
            - "traefik.enable=true"
            - "traefik.backend=airstorage-nginx"
            - "traefik.frontend.rule=Host:airstorage.nl"
            - "traefik.port=80"
            - "traefik.docker.network=public"
        depends_on:
            - rebackend

networks:
    private:
        external:
            name: private
    public:
        external:
            name: public
