version: "3.7"

services:

    frontend:
        image: "airstorage/frontend:prod"
        build:
            target: prod
            context: ./frontend

    nginx:
        command: nginx -g "daemon off";
        image: "airstorage/nginx:prod"
        build:
            target: prod
            context: ./nginx
        networks:
            - public
        labels:
            - "traefik.enable=true"
            - "traefik.backend=airstorage-nginx"
            - "traefik.frontend.rule=Host:airstorage.patrickfen.nl"
            - "traefik.port=80"
            - "traefik.docker.network=public"

networks:
    private:
        external:
            name: private
    public:
        external:
            name: public
